name: 'Release Coda pack'
description: 'Release an uploaded Coda pack'
branding:
  color: 'orange'
  icon: 'package'
author: 'Sirius Nottin'

inputs:
  packPath:
    description: 'The path to the Coda pack to release'
    required: true
    default: 'pack.ts'
  codaApiToken:
    description: 'The Coda API token to use'
    required: true
  notes:
    description: 'The release notes for the Coda pack'
    required: true

outputs:
  releasedVersion:
    description: 'The released version of the Coda pack'

runs:
  using: 'node16'
  main: 'dist/index.js'
