name: "Release Coda pack"
description: "Release an uploaded Coda pack"
branding:
  color: "orange"
  icon: "package"
author: "Troy Larson"

inputs:
  packPath:
    description: "The path to the Coda pack to release"
    required: true
    default: "pack.ts"
  codaApiToken:
    description: "The Coda API token to use"
    required: true
  notes:
    description: "The release notes for the Coda pack"
    required: true
  packVersion:
    description: "The uploaded version of the Coda pack to release"
    required: false

outputs:
  releasedVersion:
    description: "The released version of the Coda pack"

runs:
  using: "node16"
  main: "dist/index.js"
